version: '3'

volumes:
  drone_ci_data:

services:
  drone-server:
    image: drone/drone:0.8.1
    volumes:
      - drone_ci_data:/var/lib/drone/
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - DRONE_GITHUB=true
      - DRONE_LETS_ENCRYPT=true
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_OPEN=${DRONE_OPEN}
      - DRONE_ADMIN=${DRONE_ADMIN}
      - DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT}
      - DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET}
      - DRONE_SECRET=${DRONE_SECRET}

  drone-agent:
    image: drone/agent:0.8.1
    links:
      - drone-server:drone-server
    restart: always
    depends_on: [ drone-server ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=${DRONE_SECRET}